app:
  merchant:
    job:
      reconcile:
        corn: '0 0 4 * * *'

server:
  port: 8081


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:emall
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: 'none'
  sql:
    init:
      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql

logging:
  level:
    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

